### ISSUE TITLE
Problems creating new webcomponents project from cli

### ISSUE THREAD

**Issue by NikTachev** [IgniteUI/igniteui-cli#1098]
### Description  

- Ignite UI CLI version: 11.0.1
- Framework: Web Components
- Project type: ig-ts

### Steps to reproduce  

1. in a new directory run "npm install -g igniteui-cli"
2. run "ig"
3. follow instructions and select "WebComponents" as framework
4. any template
5. "Complete & Run"

### Result  

C:\workspace\Samples\test\Test1\node_modules\@web\dev-server-rollup\node_modules\whatwg-url\lib\encoding.js:2
const utf8Encoder = new TextEncoder();
                    ^

ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (C:\workspace\Samples\test\Test1\node_modules\@web\dev-server-rollup\node_modules\whatwg-url\lib\encoding.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\workspace\Samples\test\Test1\node_modules\@web\dev-server-rollup\node_modules\whatwg-url\lib\url-state-machine.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test1@0.0.0 start: `tsc && concurrently -k -r "tsc --watch" "wds" "--port=8000"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test1@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nikola.tachev\AppData\Roaming\npm-cache\_logs\2023-02-08T16_27_41_433Z-debug.log
(node:23876) UnhandledPromiseRejectionWarning: Error: Command failed: npm start -- --port=8000
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Function.execSync (C:\Users\nikola.tachev\AppData\Roaming\npm\node_modules\igniteui-cli\node_modules\@igniteui\cli-core\util\Util.js:278:49)
    at execSyncNpmStart (C:\Users\nikola.tachev\AppData\Roaming\npm\node_modules\igniteui-cli\lib\commands\start.js:18:25)
    at Object.<anonymous> (C:\Users\nikola.tachev\AppData\Roaming\npm\node_modules\igniteui-cli\lib\commands\start.js:94:21)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\nikola.tachev\AppData\Roaming\npm\node_modules\igniteui-cli\lib\commands\start.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Expected result  

Successful project creation and launch

### Attachments  

![8b1e2cd0-669b-4e12-a504-d068642b8f04](https://user-images.githubusercontent.com/115668246/217592984-f13bf403-39be-4151-abc1-b55b18fab258.jpg)

![image](https://user-images.githubusercontent.com/115668246/217593298-4033fa8e-fdc8-4ff4-a79a-f3c264ecb627.png)

Note: Does not get fixed after installing polyfills and defining components as such 

import '@webcomponents/custom-elements/custom-elements.min';
import '@webcomponents/custom-elements/src/native-shim.js';
import { defineAllComponents } from 'igniteui-webcomponents';

defineAllComponents();

Also, in the "Install Polyfills" sections of the docs there is a command missing, and index.js should be index.ts

![image](https://user-images.githubusercontent.com/115668246/217594071-201c4fbc-e717-4e49-af06-b54178202865.png)

**Comment by Lipata** [comment]
Hi, @NikTachev.

Can you send me the results from the following command in the console:

```console
ng version
```

Do you have an `nvm` locally installed? And can you tell me if you get the `Packages successfully installed` in the console output, when trying to create WC project? At what stage is the error thrown - while installing packages or while trying to run the project?

**Comment by Lipata** [comment]
Closing this, because it is working with the latest node.
